---
title: "About Me"
---

## Hi! I am Tham Wai Hong Douglas

I am an aspiring Data Analyst with a Diploma in AI and Data Science. I am passionate about turning raw data into actionable business insights.

### 🛠️ What do I do?

- **Data Cleaning & Analysis:** Python (Pandas, NumPy, yfinance)
- **Data Visualization:** Power BI
- **Databases:** SQL (MySQL)
- **Other Tools:** Git, Jupyter Notebook, Excel, Visual Studio Code, Matlab

### 📊 Recent Projects

1.  **Singapore Banks Stock Analysis** - Analyzed 5 years of stock data for DBS, OCBC and UOB. Answered 4 business questions and built an interactive PowerBI dashboard.

🔗  [View Project on GitHub](https://github.com/Salguod310/singapore-banks-stock-analysis)

2. **Quantitative Pairs Trading Strategy** - Built a pairs trading backtest for SGX-listed stocks using cointegration, backtesting and machine learning. Identified SingTel vs Capitaland as the strongest
cointegrated pair (p = 0.000229).

🔗  [View Project on GitHub](https://github.com/Salguod310/quant-pairs-trading)

### 🎓 Education
Diploma in AI & Data Science
Kaplan Singapore, Feb 2026 - October 2026

Foundation Diploma Kaplan Singapore, Aug 2025 - Feb 2026

Nitec in Social Media & Web Development ITE College West, Jan 2014 - Dec 2015


### 📫 Connect With Me

- [LinkedIn](https://linkedin.com/in/tham-wai-hong-douglas)
- [GitHub](https://github.com/Salguod310)
- [Email](mailto:douglastham_@hotmail.com)
